function [fitresult, gof] = createFitSD(TumourY, DiaphragmY)
%CREATEFIT(TUMOURY,DIAPHRAGMY)
%  Create a fit.
%
%  Data for 'Fit of CtumourY to DiaphragmY' fit:
%      X Input : TumourY
%      Y Output: DiaphragmY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2014 11:08:10


%% Fit: 'Fit of CtumourY to DiaphragmY'.
[xData, yData] = prepareCurveData( TumourY, DiaphragmY );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Robust = 'LAR';
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit of CtumourY to DiaphragmY' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'DiaphragmY vs. TumourY', 'Fit of CtumourY to DiaphragmY', 'Lower bounds (Fit of CtumourY to DiaphragmY)', 'Upper bounds (Fit of CtumourY to DiaphragmY)', 'Location', 'NorthEast' );
% Label axes
xlabel( 'TumourY' );
ylabel( 'DiaphragmY' );
grid on

% Adjust font
set( gca                             , 'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel]      ,  'FontName'   , 'AvantGarde');
% set([hLegend, gca]                   , 'FontSize'   , 8           );
set([hXLabel, hYLabel]               , 'FontSize'   , 10          );
set( hTitle                          , 'FontSize'   , 12          , ...
                                       'FontWeight' , 'bold'      );

% Adjust axes properties
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
 hold off
 
% Linear model Poly2:
%      f(x) = p1*x^2 + p2*x + p3
% Coefficients (with 95% confidence bounds):
%        p1 =     -0.3525  (-0.8803, 0.1752)
%        p2 =         6.7  (5.787, 7.614)
%        p3 =       2.449  (-0.4117, 5.31)
% 
% Goodness of fit:
%   SSE: 609.1
%   R-square: 0.911
%   Adjusted R-square: 0.9044
%   RMSE: 4.75

