function createbarchart(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 08-Apr-2014 16:00:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 1 2 3 4 ],'YGrid','on',...
    'XMinorTick','on',...
    'XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 30.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 4.5]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title({'Number of peaks in different frame'});

% Create bar
bar(yvector1);

% Create xlabel
xlabel({'Frame'});

% Create ylabel
ylabel({'Counts of significant peaks'});

