Title  = title ('Scatter plot of Diaphragm Belt & MRI Parameter for Exhalation');
XLabel = xlabel('Diaphragm Belt Parameter\it ( D [normalize]) \it ');
YLabel = ylabel('Diaphragm Height in MRI \it ( \mu [normalize])\it');

set(gca, ...
'Box'         , 'off'     , ...
'TickDir'     , 'out'     , ...
'TickLength'  , [.02 .02] , ...
'XMinorTick'  , 'on'      , ...
'YMinorTick'  , 'on'      , ...
'YGrid'       , 'on'      , ...
'XColor'      , [.3 .3 .3], ...
'YColor'      , [.3 .3 .3], ...
'YTick'       , -0.6:0.2:0.4, ...
'LineWidth'   , 1         );


set( gca                       , ...
'FontName'   , 'Helvetica' );
set([Title, XLabel, YLabel, text], ...
'FontName'   , 'AvantGarde');
set([legend, gca]             , ...
'FontSize'   , 14           );
set([XLabel, YLabel, text]  , ...
'FontSize'   , 14          );
set( Title                    , ...
'FontSize'   , 18          ); ...

print -dpng ScatterPlotofR-RESP-exhalation.png